#!/usr/bin/env bash
set -euo pipefail

# Write public/_redirects so /md/ paths qdrant.tech has moved redirect here too.
#
# The rules come from qdrant.tech/redirects.txt, generated at build time by
# automation/generate-redirects-table.py in the landing_page repo. That file
# merges the _redirects file, the netlify.toml rules and Hugo's `aliases:` front
# matter, none of which is otherwise fetchable. It is the single owner of these
# rules — never hand-maintain a rule list here, or the two will diverge.
#
# Ordering matters: Netlify processes _redirects before netlify.toml, so these
# rules are matched before the `/md/* -> search.qdrant.tech` proxy and answer at
# the edge without reaching the origin. Everything else still proxies as before.

TABLE_URL="${REDIRECTS_URL:-https://qdrant.tech/redirects.txt}"
PUBLIC_DIR="${1:-public}"
OUTPUT="${PUBLIC_DIR}/_redirects"
TABLE=$(mktemp)
trap 'rm -f "$TABLE"' EXIT

# A missing table means /md/ misses 404 exactly as they did before this existed,
# which is not worth failing a site deploy over. Warn and carry on.
if ! curl -fsS --max-time 30 "$TABLE_URL" -o "$TABLE"; then
  echo "warning: could not fetch $TABLE_URL — deploying without /md/ redirects" >&2
  exit 0
fi

{
  echo "# Generated by scripts/generate_md_redirects.sh from ${TABLE_URL}."
  echo "# Do not edit. To change a rule, change it in the landing_page repo."
  awk '
    /^#/ || NF < 2 { next }
    # External targets belong to qdrant.tech, not to this mirror.
    $2 ~ /^(https?:)?\/\// { next }
    {
      # The mirror addresses a section as ?s=, not as a fragment.
      sub(/#/, "?s=", $2)
      print "/md" $1 "  /md" $2 "  " ($3 == "" ? "301" : $3)
    }
  ' "$TABLE"
} > "$OUTPUT"

echo "wrote $OUTPUT with $(grep -c '^/md' "$OUTPUT") /md/ redirect rules"
